[package]
name = "rust-vanitygen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { version = "^0.29.2", features = ["rand", "serde"] }
